### ISSUE TITLE
About delta pose update 

### ISSUE THREAD

**Issue by FangGet** [cashiwamochi/SimpleBundleAdjustment#1]
it seems that you compute delta pose on se(3) with left disturbance model, but I noticed that you update the pose with right multiply? why?

‘’‘
// Update!
   vm_poses[i] = vm_poses[i] * delta_SE3;
‘’’

**Comment by cashiwamochi** [comment]
Thanks for your comment.
It's my mistake and I ensured that optimization worked correctly if I fixed it.

**Comment by FangGet** [comment]
ok, I get it.
