### ISSUE TITLE
Why adding noise to target data for bundle adjustment?

### ISSUE THREAD

**Issue by sandeepnmenon** [cashiwamochi/SimpleBundleAdjustment#4]
Why is the target data added with noise of the initial estimate?
https://github.com/cashiwamochi/SimpleBundleAdjustment/blob/2b4e5249835c5a798fc1ddd03f101e8579d70213/ba_example.cc#L183

When I add noise, I see that the bundle adjustment is converging at my initial estimate itself. So why add the noise?

**Comment by cashiwamochi** [comment]
I added noise because I want to show this bundle adjustment minimize reprojection error expectedly. If no noise is added, reprojection error does not change, so we cannot see if it works, or not.
